import { notFound } from 'next/navigation';
import { sb } from '../../../lib/supabase';

export const revalidate = 60;
export const dynamicParams = true;

// v1 placeholder host: real per-idea tool routes are generated by the runner in Phase 3.
// For now this renders a "coming soon" if a tool row exists and is live.
export default async function ToolPage({ params }: { params: { id: string } }) {
  const { data } = await sb()
    .from('landing_pages')
    .select('id,headline,live,content')
    .eq('id', params.id)
    .eq('live', true)
    .maybeSingle();
  if (!data) notFound();
  return (
    <main style={{ maxWidth: 720, margin: '0 auto', padding: '56px 20px' }}>
      <h1>{(data as any).headline}</h1>
      <p style={{ color: '#475467' }}>Tool loading…</p>
    </main>
  );
}
